### ISSUE TITLE
PORTFOLIO—DESIGN-BLUEPRINT

### ISSUE THREAD

**Issue by BFGriffith** [BFGriffith/Basic-Portfolio#1]
## SPECIFICATIONS:
1. **COLORS:**
   - [x] teal color (used for headings and backgrounds) = `#4aaaa5`
   - [x] regular font color (used for paragraphs and all text besides the headings) = `#777777`
   - [ ] main header background color = `#ffffff`
   - [ ] main header border color = `#cccccc`
   - [ ] footer background color = `#666666`
   - [ ] main content background color = `#ffffff`
   - [ ] main content border color = `#dddddd`
   - _pro-TIP: use the [Eye-Dropper](https://chrome.google.com/webstore/detail/eye-dropper/hmdcmlfkchdmnmnmheododdhjedfccka) Chrome extension to find the colors used on web pages_
2. **FONTS:**
   - [x] Heading fonts use `font-family: 'Georgia', Times, Times New Roman, serif;`
   - [x] All other fonts use `'Arial', 'Helvetica Neue', Helvetica, sans-serif;`
3. **PROFILE-IMAGE on `index.html`:**
   - Use a picture of yourself. If you don't have a picture, you can grab a placeholder image from [LoremPixel](http://lorempixel.com/). Save the images to your `images` folder
4. **PORTFOLIO-IMAGES:**
   - Placeholder images can be found [LoremPixel](http://lorempixel.com/); save the images to your `images` folder.
5. **SOCIAL-link images (e.g. Github, LinkedIn, and StackOverflow):**
   - These images can be found on [IconFinder](https://www.iconfinder.com/); save the images to your `images` folder.
6. **BACKGROUND-IMAGES:**
   - [x] The background pattern used was found on [Subtle Patterns](http://subtlepatterns.com/); you can browse through that site and find whichever pattern you like.
7. **DIMENSIONS:**
   - [ ] the width of the entire content area is `960px` wide
   - [ ] the width of the main section content is `650px` wide
   - [ ] the width of the sidebar is `270px`
   - _pro-TIP: use the [Page-Ruler](https://chrome.google.com/webstore/detail/page-ruler/jlpkojjdgbllmedoapgfodplfhcbnbpn/related?hl=en) extension to measure the size of elements_

---
### “BONUS”:godmode:(stretch-goals)
1. Make the pages more sophisticated by adding styling to text links, image links, and buttons when the mouse hovers over them. A CSS hover tutorial can be found [here](http://www.codeitpretty.com/2013/06/how-to-use-css-hover-effects.html). You can use [Adobe Kuler](https://color.adobe.com/create/color-wheel/) to find colors that match the theme (In this case, the primary color is Teal `#4aaaa5`).
2. Make a sticky-footer. You will notice the dark grey footer will always rest just below the content. This is fine when the content is long, but if there isn't much content in the body the footer could rest in the middle of the page. Try to code the footer in a way that it will always remain at the bottom of the page, no matter how short the content is. A sticky footer tutorial can be found [here](http://ryanfait.com/html5-sticky-footer/). Please note, I am not talking about positioning the footer as “fixed” to the browser. See screenshots examples:
   - [No sticky footer](bonus_assets/nosticky.jpg)
   - [Has sticky footer](bonus_assets/stickyfooter.jpg)
